language: node_js

node_js:
  - "12"

dist: trusty

# Trigger build only when one of the following conditions is met
if: type = pull_request OR branch = master OR tag IS present

addons:
  chrome: stable
  sonarcloud:
    organization: "ontotext-ad"
  # Needed for Cypress tests
  apt:
    packages:
      - libgconf-2-4


## Cache Cypress binary
## to avoid downloading Cypress again and again
cache:
  directories:
    - ~/.cache

jobs:
  include:
    - stage: test
      script:
        - npm run lint
        - npm run test
        - npm run cy:ci
      if: type = pull_request
    - stage: npm release onto-search
      script: npm run build:onto-search-prod
      if: tag IS present
      deploy:
        - provider: npm
          skip_cleanup: true
          api_key: $NPM_TOKEN
          email: $NPM_MAIL
          on:
            tags: true
